
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "IDENTIFIER INTEGER KEYWORD STRING SYMBOLstatement : expressionexpression : expression SYMBOL expressionexpression : '(' expression ')' expression : INTEGERexpression : STRINGexpression : IDENTIFIER"
    
_lr_action_items = {'(':([0,3,7,],[3,3,3,]),'INTEGER':([0,3,7,],[4,4,4,]),'STRING':([0,3,7,],[5,5,5,]),'IDENTIFIER':([0,3,7,],[6,6,6,]),'$end':([1,2,4,5,6,9,10,],[0,-1,-4,-5,-6,-2,-3,]),'SYMBOL':([2,4,5,6,8,9,10,],[7,-4,-5,-6,7,7,-3,]),')':([4,5,6,8,9,10,],[-4,-5,-6,10,-2,-3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,3,7,],[2,8,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> expression','statement',1,'p_statement_expr','views.py',182),
  ('expression -> expression SYMBOL expression','expression',3,'p_expression_binop','views.py',186),
  ('expression -> ( expression )','expression',3,'p_expression_group','views.py',190),
  ('expression -> INTEGER','expression',1,'p_expression_number','views.py',194),
  ('expression -> STRING','expression',1,'p_expression_string','views.py',198),
  ('expression -> IDENTIFIER','expression',1,'p_expression_identifier','views.py',202),
]
